server:
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: NEVER
    include-exception: false
  servlet:
    context-path: /pesa-pal/problem3/api/v1

spring:
  gson:
    pretty-printing: true
  jackson:
    default-property-inclusion: NON_NULL
  application:
    name: Pesa-Pal Problem3